services:
  face-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env.development
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-app_perfil}:${POSTGRES_PASSWORD:-dev_password}@host.docker.internal:5433/${POSTGRES_DB:-app_perfil_development}?sslmode=disable
      PORT: "8080"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
